spring.application.name=aws
spring.kafka.bootstrap-servers=[::1]:9092

#groud-id is for this consumer, kafka uses it to identify and track read messages
spring.kafka.consumer.group-id=aws-processor

#auto offset means that if this consumer connects to kafka for the first time then start from the oldest message
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#this is the default dto, tells json deseralizer to know which class skeleton the data follows. after this the data
#goes into the listen() method as parameter
spring.kafka.consumer.properties.spring.json.value.default.type=com.billing.aws.RawUsageLogDTO
spring.kafka.consumer.properties.spring.json.use.type.headers=false
